baseURL = "https://midiroot.com/"
title = "Taleeb Midi"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = "UA-106773326-1"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
  description = "Just some of the interesting Dev/Ops, Linux and technology related findings. I am using these posts as reference, a writing experience and a place to share what I find interesting. Let's connect"

  title404 = "I see you come to a lost page, now you can blame me or blame yourself... yourself alone!"

[params.assets]
  favicon = "favicon.ico"
  customCSS = ["css/prism.css"]
  customJS = ["js/prism.js"]
  gopher = "37dfbf966b94ed2be5a32694dcf15b793d4360d3" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
  prefix = "All rights reserved"
  holder = "Taleeb Midi"
  startYear = "2017"
  suffix = ""

[params.settings]
  # date & time format: https://golang.org/pkg/time/
  dateFormat = "2006, Jan 02"
  listDateFormat = "2006, Jan 02"
  archiveDateFormat = "Jan 02"
  hideEntryNavigation = ["page"] # boolean / array of sections
  hideSocialMenu = false
  showReadingTime = false
  taxonomyCloudShuffle = true

[params.sidebar]
  enable = true
  sticky = true

[params.widgets]
  homepage = ["recent_posts"]
  sidebar = ["about","taxonomy_cloud"]

[params.opengraph.facebook]
  admins = [] # array of Facebook IDs
  appID = ""
  pageID = ""

[params.opengraph.twitter]
  page = "midi_onze" # Twitter page username

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.social]
  linkedin = "taleebmidi"
  github = "tmidi"
  twitter = "midi_onze"
  # codepen = ""
  # email = ""
  # facebook = ""
  # gitlab = ""
  # instagram = ""
  # telegram = ""
  # google_scholar = ""

[params.social.config]
  platforms = ["linkedin","github","twitter"]

[params.widgets]
homepage = ["recent_posts","social_menu"]
sidebar = ["about","taxonomy_cloud"]

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Home"
  weight = -10
  identifier = "tmidi"
  url = "https://midiroot.com/"

[blackfriday]
hrefTargetBlank = true

[languages]
  # edit this block for your own language
  [languages.en]
  lang = "en"
  languageName = "English"
  weight = 1
