baseURL = "https://midiroot.com/"
title = "T. Midi"
copyright = "© All rights reserved."

theme = "minimo"

disqusShortname = ""
googleAnalytics = "UA-106773326-1"
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "My own Linux and Dev/Ops references, but feel free to use."
  dateFormat = "2006, Jan 2"
  copyrightOwner = "T.Midi"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/prism.css"]
  customJS = ["js/prism.js"]
  hideSocialMenu = false
  showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Taleeb Midi"

[author.social]
  codepen = ""
  email = ""
  facebook = ""
  github = "tmidi"
  instagram = ""
  twitter = "midi_onze"
  linkedin = "taleebmidi"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -70
  identifier = "tmidi"
  url = "https://midiroot.com/"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
